Catch missing CONFIG_PREEMPT_NOTIFIERS on kernels >= 2.6.33
The new hw_breakpoint subsystem of 2.6.33 no longer allows us to use the
preemption notifier emultion based on breakpoints. Warn the user that
there is no way to use kvm-kmod without CONFIG_KVM=m.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -127,6 +127,21 @@ if [ ! -n "$force_build" ]; then
 	fi
 fi
 
+. "$kerneldir/.config"
+if [ "$CONFIG_PREEMPT_NOTIFIERS" = "" ]; then
+	if [ $kernel_subversion -ge 33 ]; then
+		echo
+		echo "Error: kernel lacks KVM support, keeping preemption notifiers disabled."
+		echo "Since kernel 2.6.33, kvm-kmod is no longer able to provide a workaround"
+		echo "implementation for this feature. You have to enable KVM as module(!) in your"
+		echo "kernel first, rebuild and install it."
+		echo
+		exit 1
+	fi
+	echo "WARNING: kvm-kmod will emulate missing preemption notifiers."
+	echo "Do not benchmark this system!"
+fi
+
 if [ -n "$no_uname" -a "$want_module" ]; then
 	depmod_version=$kernel_version
 fi
